# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LineEditClass.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(599, 324)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 101, 21))
        self.label.setObjectName("label")
        self.labelText = QtWidgets.QLabel(Dialog)
        self.labelText.setGeometry(QtCore.QRect(10, 240, 581, 71))
        self.labelText.setText("")
        self.labelText.setObjectName("labelText")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(120, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(270, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_3.setObjectName("label_3")
        self.lineEditCode = QtWidgets.QLineEdit(Dialog)
        self.lineEditCode.setGeometry(QtCore.QRect(120, 20, 113, 20))
        self.lineEditCode.setObjectName("lineEditCode")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 71, 21))
        self.label_4.setObjectName("label_4")
        self.lineEditHistory = QtWidgets.QLineEdit(Dialog)
        self.lineEditHistory.setGeometry(QtCore.QRect(120, 90, 113, 20))
        self.lineEditHistory.setObjectName("lineEditHistory")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 91, 16))
        self.label_5.setObjectName("label_5")
        self.lineEditGeography = QtWidgets.QLineEdit(Dialog)
        self.lineEditGeography.setGeometry(QtCore.QRect(120, 120, 113, 20))
        self.lineEditGeography.setObjectName("lineEditGeography")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 47, 13))
        self.label_6.setObjectName("label_6")
        self.lineEditTotal = QtWidgets.QLineEdit(Dialog)
        self.lineEditTotal.setEnabled(False)
        self.lineEditTotal.setGeometry(QtCore.QRect(120, 170, 113, 20))
        self.lineEditTotal.setObjectName("lineEditTotal")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 210, 71, 16))
        self.label_7.setObjectName("label_7")
        self.lineEditPercentage = QtWidgets.QLineEdit(Dialog)
        self.lineEditPercentage.setEnabled(False)
        self.lineEditPercentage.setGeometry(QtCore.QRect(120, 210, 113, 20))
        self.lineEditPercentage.setObjectName("lineEditPercentage")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter your name"))
        self.pushButton.setText(_translate("Dialog", "Click"))
        self.label_3.setText(_translate("Dialog", "Enter your code"))
        self.label_4.setText(_translate("Dialog", "History Marks"))
        self.label_5.setText(_translate("Dialog", "Geography Marks"))
        self.label_6.setText(_translate("Dialog", "total"))
        self.label_7.setText(_translate("Dialog", "Precentage"))
