# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LineEditClass.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 210, 291, 21))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(120, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 150, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_3.setObjectName("label_3")
        self.lineEditCode = QtWidgets.QLineEdit(Dialog)
        self.lineEditCode.setGeometry(QtCore.QRect(120, 20, 113, 20))
        self.lineEditCode.setObjectName("lineEditCode")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 71, 21))
        self.label_4.setObjectName("label_4")
        self.lineEditHistory = QtWidgets.QLineEdit(Dialog)
        self.lineEditHistory.setGeometry(QtCore.QRect(120, 90, 113, 20))
        self.lineEditHistory.setObjectName("lineEditHistory")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 120, 91, 16))
        self.label_5.setObjectName("label_5")
        self.lineEditGeography = QtWidgets.QLineEdit(Dialog)
        self.lineEditGeography.setGeometry(QtCore.QRect(120, 120, 113, 20))
        self.lineEditGeography.setObjectName("lineEditGeography")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enter your name"))
        self.pushButton.setText(_translate("Dialog", "Click"))
        self.label_3.setText(_translate("Dialog", "Enter your code"))
        self.label_4.setText(_translate("Dialog", "History Marks"))
        self.label_5.setText(_translate("Dialog", "Geography Marks"))
